/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipeKeyRouteImport } from './routes/$recipeKey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as ComponentsRecipeKeyRouteImport } from './routes/components/$recipeKey'
import { Route as AppsAppKeyRouteImport } from './routes/apps/$appKey'

const RecipeKeyRoute = RecipeKeyRouteImport.update({
  id: '/$recipeKey',
  path: '/$recipeKey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRecipeKeyRoute = ComponentsRecipeKeyRouteImport.update({
  id: '/components/$recipeKey',
  path: '/components/$recipeKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppKeyRoute = AppsAppKeyRouteImport.update({
  id: '/apps/$appKey',
  path: '/apps/$appKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$recipeKey': typeof RecipeKeyRoute
  '/apps/$appKey': typeof AppsAppKeyRoute
  '/components/$recipeKey': typeof ComponentsRecipeKeyRoute
  '/apps/': typeof AppsIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$recipeKey': typeof RecipeKeyRoute
  '/apps/$appKey': typeof AppsAppKeyRoute
  '/components/$recipeKey': typeof ComponentsRecipeKeyRoute
  '/apps': typeof AppsIndexRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$recipeKey': typeof RecipeKeyRoute
  '/apps/$appKey': typeof AppsAppKeyRoute
  '/components/$recipeKey': typeof ComponentsRecipeKeyRoute
  '/apps/': typeof AppsIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$recipeKey'
    | '/apps/$appKey'
    | '/components/$recipeKey'
    | '/apps/'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$recipeKey'
    | '/apps/$appKey'
    | '/components/$recipeKey'
    | '/apps'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/$recipeKey'
    | '/apps/$appKey'
    | '/components/$recipeKey'
    | '/apps/'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipeKeyRoute: typeof RecipeKeyRoute
  AppsAppKeyRoute: typeof AppsAppKeyRoute
  ComponentsRecipeKeyRoute: typeof ComponentsRecipeKeyRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$recipeKey': {
      id: '/$recipeKey'
      path: '/$recipeKey'
      fullPath: '/$recipeKey'
      preLoaderRoute: typeof RecipeKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$recipeKey': {
      id: '/components/$recipeKey'
      path: '/components/$recipeKey'
      fullPath: '/components/$recipeKey'
      preLoaderRoute: typeof ComponentsRecipeKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appKey': {
      id: '/apps/$appKey'
      path: '/apps/$appKey'
      fullPath: '/apps/$appKey'
      preLoaderRoute: typeof AppsAppKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipeKeyRoute: RecipeKeyRoute,
  AppsAppKeyRoute: AppsAppKeyRoute,
  ComponentsRecipeKeyRoute: ComponentsRecipeKeyRoute,
  AppsIndexRoute: AppsIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
