/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipeKeyRouteImport } from './routes/$recipeKey'
import { Route as IndexRouteImport } from './routes/index'

const RecipeKeyRoute = RecipeKeyRouteImport.update({
  id: '/$recipeKey',
  path: '/$recipeKey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$recipeKey': typeof RecipeKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$recipeKey': typeof RecipeKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$recipeKey': typeof RecipeKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$recipeKey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$recipeKey'
  id: '__root__' | '/' | '/$recipeKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipeKeyRoute: typeof RecipeKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$recipeKey': {
      id: '/$recipeKey'
      path: '/$recipeKey'
      fullPath: '/$recipeKey'
      preLoaderRoute: typeof RecipeKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipeKeyRoute: RecipeKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
